/**
 * Created by asaf on 27/04/2016.
 */

let strings = {
    appName: "נטו - עמלות",
    email: "דואר אלקטרוני",
    name: "שם פרטי",
    familyName: "שם משפחה",
    password: "סיסמה",
    disconnect: "התנתק",
    connect: "התחבר",
    register: "הרשמה",
    needAccount: "צריך חשבון?",
    sendRegisterRequest: "שלח בקשה להרשם",
    loginErrorMessage: "שם משתמש או סיסמה שגויים",
    dashboard: "ראשי",
    commissions: "עמלות",
    salaries: "שכר",
    agents: "סוכנים",
    agentsAndPartnerships: "סוכנים ושותפויות",
    settings: "הגדרות",
    partnerships: "שותפויות",
    totalValue: "סה״כ ",
    totalAgents: "סה״כ סוכנים פעילים",
    totalPortfolio: "סה״כ גודל תיק",
    comapnyPart: "סה״כ לחברת נטו",
    load: "טען",
    dragFileHere: "גרור קובץ עמלות לכאן",
    companyAssignment: "שיוך לחברה",
    validDate: "תאריך נכונות",
    paymentMonth: "חודש שכר",
    uploadFile: "העלה קובץ",
    editFiles: "עריכת קבצים",
    notes: "הערות",
    taxIncluded: "כולל מע״מ",
    taxNotIncluded: "לא כולל מע״מ",
    tax: "מע״מ",
    newAgent: "סוכן חדש",
    newPayment: "עמלה חדשה",
    newPartnership: "שותפות חדשה",
    agentPageDetails: "הגדרות סוכן",
    agentSalaryPage: "פרוט שכר",
    agentPageName: "שם פרטי",
    agentPageFamilyName: "שם משפחה",
    agentPageId: "מזהה",
    agentPagePhone: "טלפון",
    agentPageFax: "פקס",
    agentPageEmail: "אימייל",
    active: "פעיל",
    notActive: "לא פעיל",
    agentPageTableTitle: "עמלות",
    cancel: "ביטול",
    save: "שמירה",
    exit: "יציאה",
    partnershipPageDetails: "הגדרות שותפות",
    partnershipPageName: "שם פרטי",
    partnershipPageFamilyName: "שם משפחה",
    partnershipPageId: "מזהה",
    partnershipPagePhone: "טלפון",
    partnershipPageFax: "פקס",
    partnershipPageEmail: "אימייל",
    totalSalary: "סה״כ שכר (כולל מע״מ)",
    incomes: "הכנסות",
    expenses: "הוצאות",
    nifraim: "נפרעים",
    bonus: "בונוס",
    heikef: "היקף",
    manualIncome: "שונות",
    newIncome: "הכנסה חדשה",
    editIncome: "עריכת הכנסה",
    newExpense: "הוצאה חדשה",
    editExpense: "עריכת הוצאה",
    generateExcelFile: "יצא לקובץ אקסל",
    newCompany: "חברה חדשה"

}

export { strings }