/**
 * Created by asaf on 27/04/2016.
 */

let strings = {
    appName: "נטו - עמלות סוכן",
    email: "דואר אלקטרוני",
    password: "סיסמה",
    disconnect: "התנתק",
    connect: "התחבר",
    needAccount: "צריך חשבון?",
    sendRegisterRequest: "שלח בקשה להרשם",
    loginErrorMessage: "שם משתמש או סיסמה שגויים",
    dashboard: "ראשי",
    commissions: "עמלות",
    agents: "סוכנים",
    agentsAndPartnerships: "סוכנים ושותפויות",
    partnerships: "שותפויות",
    totalCommissions: "סה״כ עמלות",
    totalAgents: "סה״כ סוכנים",
    totalInvestments: "סה״כ גודל תיק",
    totalInvestmentsChange: "עמלות (מיליונים)",
    load: "טען",
    dragFileHere: "גרור קובץ עמלות לכאן",
    companyAssignment: "שיוך לחברה",
    validDate: "תאריך נכונות",
    paymentMonth: "חודש שכר",
    uploadFile: "העלה קובץ",
    editFiles: "עריכת קבצים",
    notes: "הערות",
    taxIncluded: "כולל מע״מ",
    taxNotIncluded: "לא כולל מע״מ",
    tax: "מע״מ",
    newAgent: "סוכן חדש",
    newPayment: "עמלה חדשה",
    newPartnership: "שותפות חדשה",
    agentPageDetails: "הגדרות סוכן",
    agentSalaryPage: "פרוט שכר",
    agentPageName: "שם פרטי",
    agentPageFamilyName: "שם משפחה",
    agentPageId: "מזהה",
    agentPagePhone: "טלפון",
    agentPageFax: "פקס",
    agentPageEmail: "אימייל",
    active: "פעיל",
    notActive: "לא פעיל",
    agentPageTableTitle: "עמלות",
    agentPageSave: "שמירה",
    agentPageExit: "יציאה",
    partnershipPageDetails: "הגדרות שותפות",
    partnershipPageName: "שם פרטי",
    partnershipPageFamilyName: "שם משפחה",
    partnershipPageId: "מזהה",
    partnershipPagePhone: "טלפון",
    partnershipPageFax: "פקס",
    partnershipPageEmail: "אימייל",
    totalSalary: "סה״כ שכר (כולל מע״מ)",
    incomes: "הכנסות",
    manualIncomes: "הכנסה ידנית",
    expenses: "הוצאות",
    nifraim: "נפרעים",
    bonus: "בונוס",
    heikef: "היקף",
    newIncome: "הכנסה חדשה",
    newExpense: "הוצאה חדשה"

}

export { strings }